### ISSUE TITLE
Deploy version 1.9.2 javadocs and update wiki

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava-legacy#31]

**Comment by heuermh** [comment]
@josemduarte I'd like to cut a new biojava-legacy release (#54) to pick up security fixes in dependencies, but still haven't figured out how to update the legacy javadocs.  Looks like I should add them here https://github.com/biojava/biojava.github.io/tree/master/docs ?

**Comment by josemduarte** [comment]
Correct, that's how we are doing it lately. Then also update the link in the home page https://biojava.org/

**Comment by heuermh** [comment]
Thanks, will do!
